### ISSUE TITLE
Windows build on GitHub Actions is failing

### ISSUE THREAD

**Issue by brian-rose** [brian-rose/minimalf2py#2]
The build and install stage seems to work without error on Windows, but then when we try to `import minimalf2py` we get this error:
```
  python -c "import minimalf2py"
  shell: C:\windows\System32\WindowsPowerShell\v1.0\powershell.EXE -command ". '{0}'"
 env:
    CONDA: C:\Miniconda3
    CONDA_PKGS_DIR: C:\Users\runneradmin\conda_pkgs_dir
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\a\minimalf2py\minimalf2py\minimalf2py\__init__.py", line 3, in <module>
    from .add import zadd
ImportError: DLL load failed while importing add: The specified module could not be found.
Error: Process completed with exit code 1.
```

e.g. here: https://github.com/brian-rose/minimalf2py/runs/1965368651?check_suite_focus=true#step:5:11

**Comment by brian-rose** [comment]
Fixed by adding [this critical line](https://github.com/brian-rose/minimalf2py/blob/e1b10c79b3067cd89b39c766fb1cc628835df0eb/.github/workflows/build-and-test.yaml#L41) to the action script.

Thanks for [this tip on twitter!](https://twitter.com/sci_vision/status/1388132792622592004).
